import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { SearchProvider } from "@/components/SearchContext";
import { BasketProvider } from "@/components/BasketContext";
import { AuthProvider } from "../../components/AuthContext";
import Header from "../../components/header";
import Footer from "../../components/footer";
import "../../styles/layout/_globals.scss";

export const metadata: Metadata = {
  title: "ShopEase",
  description: "new store Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthProvider>
          <SearchProvider>
            <BasketProvider>
              <div className="ALL">
                <Header />
                <main>{children}</main>
                <Footer />
              </div>
            </BasketProvider>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
